# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0

complexity:
  CyclomaticComplexMethod:
    active: false
  ComplexCondition:
    active: false
  LongMethod:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false

style:
  MagicNumber:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
