# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0

FROM julia:1.12.2@sha256:e0976e892bebcbd29ea15b6660b5e0d9b20e03a6adb257f2ee505919d4495fe4

RUN useradd --create-home --uid 10001 appuser

USER appuser
